require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'demo01' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'

  target 'demo01Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'demo01-tvOS' do
  # Pods for demo01-tvOS

  target 'demo01-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
