/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.olc.maguhf;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int bg_back=0x7f050029;
        public static final int black=0x7f050023;
        public static final int black_light=0x7f050024;
        public static final int blue=0x7f050025;
        public static final int contents_text=0x7f050003;
        /**  zxing 
         */
        public static final int dark_blue=0x7f050037;
        public static final int dark_gray=0x7f05001c;
        public static final int encode_view=0x7f050004;
        public static final int friend_message_text_gray=0x7f05002b;
        public static final int gold=0x7f050022;
        public static final int gray=0x7f05001f;
        public static final int green_forlist=0x7f050028;
        public static final int help_button_view=0x7f050005;
        public static final int help_view=0x7f050006;
        public static final int index_num=0x7f05002e;
        /**  详情字体颜色 
         */
        public static final int info_text_black_color=0x7f050034;
        public static final int info_text_blue_color=0x7f050035;
        public static final int item_normal=0x7f05002d;
        public static final int item_press=0x7f05002c;
        public static final int item_subtilte_color=0x7f050033;
        public static final int light_blue=0x7f050001;
        public static final int light_blue_titlecolor=0x7f050038;
        public static final int light_gray=0x7f050002;
        public static final int light_gray_1=0x7f050020;
        public static final int light_gray_2=0x7f050021;
        public static final int pad_bg_back=0x7f05002a;
        public static final int pad_blue_color=0x7f050036;
        public static final int pad_top_blue_color=0x7f050000;
        public static final int possible_result_points=0x7f050007;
        public static final int read_only_color=0x7f05000a;
        public static final int red=0x7f050026;
        public static final int red_1=0x7f050027;
        public static final int result_image_border=0x7f050008;
        public static final int result_minor_text=0x7f050009;
        public static final int result_points=0x7f05000b;
        public static final int result_text=0x7f05000c;
        public static final int result_view=0x7f05000d;
        public static final int sbc_header_text=0x7f05000e;
        public static final int sbc_header_view=0x7f05000f;
        public static final int sbc_layout_view=0x7f050011;
        public static final int sbc_list_item=0x7f050010;
        public static final int sbc_page_number_text=0x7f050012;
        public static final int sbc_snippet_text=0x7f050013;
        /**  特殊颜色 
         */
        public static final int shadow_color=0x7f05002f;
        public static final int share_text=0x7f050014;
        public static final int share_view=0x7f050015;
        public static final int status_text=0x7f050017;
        public static final int status_view=0x7f050016;
        public static final int theme_color=0x7f05001d;
        public static final int time_color1=0x7f050031;
        public static final int time_color_copy=0x7f050030;
        public static final int time_color_pad=0x7f050032;
        public static final int transparent=0x7f050018;
        public static final int viewfinder_frame=0x7f050019;
        public static final int viewfinder_laser=0x7f05001a;
        public static final int viewfinder_mask=0x7f05001b;
        public static final int white=0x7f05001e;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int backmenu=0x7f020001;
        public static final int btn_bg=0x7f020002;
        public static final int btn_bg1=0x7f020003;
        public static final int btn_bg_disable=0x7f020004;
        public static final int btn_bg_normal=0x7f020005;
        public static final int btn_bg_press=0x7f020006;
        public static final int btn_main_help=0x7f020007;
        public static final int button_selector=0x7f020008;
        public static final int ic_launcher=0x7f020009;
        public static final int ic_launcher1=0x7f02000a;
        public static final int ic_launcher3=0x7f02000b;
        public static final int ic_launcherc=0x7f02000c;
        public static final int ic_loading_bg=0x7f02000d;
        public static final int ic_loading_white_01=0x7f02000e;
        public static final int ic_loading_white_02=0x7f02000f;
        public static final int ic_loading_white_03=0x7f020010;
        public static final int ic_loading_white_04=0x7f020011;
        public static final int ic_loading_white_05=0x7f020012;
        public static final int ic_loading_white_06=0x7f020013;
        public static final int ic_loading_white_07=0x7f020014;
        public static final int ic_loading_white_08=0x7f020015;
        public static final int ic_loading_white_09=0x7f020016;
        public static final int ic_loading_white_10=0x7f020017;
        public static final int ic_loading_white_11=0x7f020018;
        public static final int ic_loading_white_12=0x7f020019;
        public static final int item_content_bg=0x7f02001a;
        public static final int item_content_big_bg=0x7f02001b;
        public static final int item_content_big_normal=0x7f02001c;
        public static final int item_content_big_press=0x7f02001d;
        public static final int item_content_normal=0x7f02001e;
        public static final int item_content_press=0x7f02001f;
        public static final int listback=0x7f020020;
        public static final int menu=0x7f020021;
        public static final int progress_drawable_white=0x7f020022;
        public static final int settings=0x7f020023;
    }
    public static final class id {
        public static final int BtnKill=0x7f0a0027;
        public static final int BtnLock=0x7f0a001f;
        public static final int Btn_ReadPower=0x7f0a0019;
        public static final int Btn_SetPower=0x7f0a001a;
        public static final int Lockpassword=0x7f0a001e;
        public static final int Radio_AccessRFU=0x7f0a0020;
        public static final int Radio_EPC=0x7f0a000b;
        public static final int Radio_OPEN=0x7f0a0022;
        public static final int Radio_RFU=0x7f0a000a;
        public static final int Radio_TID=0x7f0a000c;
        public static final int Radio_USER=0x7f0a000d;
        public static final int Radio_killRFU=0x7f0a0021;
        public static final int Radio_lock=0x7f0a0024;
        public static final int Radio_lockforever=0x7f0a0025;
        public static final int Radio_openforever=0x7f0a0023;
        public static final int action_settings=0x7f0a002b;
        public static final int address=0x7f0a000f;
        public static final int bst_readEPC=0x7f0a0004;
        public static final int bst_readTid=0x7f0a0005;
        public static final int btn_dubiaoqian=0x7f0a0016;
        public static final int btn_main_back=0x7f0a0006;
        public static final int btn_main_systemExit=0x7f0a0000;
        public static final int btn_readepc=0x7f0a0008;
        public static final int btn_xiebiaoqian=0x7f0a0014;
        public static final int datalength=0x7f0a0010;
        public static final int et_power=0x7f0a0018;
        public static final int id_tv_loadingmsg=0x7f0a0028;
        public static final int inputdata=0x7f0a0012;
        public static final int killpassword=0x7f0a0026;
        public static final int list1_layout=0x7f0a0002;
        public static final int list_deviceitem=0x7f0a0003;
        public static final int password=0x7f0a000e;
        public static final int readepc=0x7f0a001d;
        public static final int resultView=0x7f0a0015;
        public static final int sex=0x7f0a0009;
        public static final int textCountNo=0x7f0a002a;
        public static final int textEPC=0x7f0a0007;
        public static final int textTID=0x7f0a0029;
        public static final int textView1=0x7f0a0001;
        public static final int textViewPower=0x7f0a0017;
        public static final int tx_line=0x7f0a0011;
        public static final int tx_resultView=0x7f0a0013;
        public static final int txt_version=0x7f0a001b;
        public static final int wv_help=0x7f0a001c;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int activity_readwrite=0x7f030001;
        public static final int activity_setting=0x7f030002;
        public static final int activityhelp=0x7f030003;
        public static final int activitylock=0x7f030004;
        public static final int dialog=0x7f030005;
        public static final int listviewitem=0x7f030006;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class raw {
        public static final int beep_err=0x7f040000;
        public static final int beep_ok=0x7f040001;
        public static final int chimes=0x7f040002;
        public static final int didi=0x7f040003;
        public static final int dudu=0x7f040004;
    }
    public static final class string {
        public static final int App_version=0x7f070023;
        public static final int Demodulation_threshold=0x7f070041;
        public static final int Fail=0x7f070046;
        public static final int Failure_Rate=0x7f070049;
        public static final int IF_Amplifier=0x7f070040;
        public static final int Kill_Tag=0x7f07001e;
        public static final int Lable_Length=0x7f070018;
        public static final int Lable_Password=0x7f070016;
        public static final int Lable_Read_Memory=0x7f070015;
        public static final int Lable_Write=0x7f070014;
        public static final int Lable_data=0x7f070019;
        public static final int Lable_data_write=0x7f07001a;
        public static final int Lable_result=0x7f07001b;
        public static final int Lable_start_address_hint=0x7f070017;
        public static final int Lable_write_null=0x7f07001c;
        public static final int Lock_TAG=0x7f07001d;
        public static final int Mixer=0x7f07003f;
        public static final int Power_out=0x7f07000a;
        public static final int Power_out_Read=0x7f07000b;
        public static final int Power_out_Setting=0x7f07000c;
        public static final int Power_out_test=0x7f07003d;
        public static final int Read=0x7f070042;
        public static final int ReadError09=0x7f070038;
        public static final int ReadError16=0x7f070039;
        public static final int ReadErrorA0=0x7f07003c;
        public static final int ReadErrorA3=0x7f07003a;
        public static final int ReadErrorA4=0x7f07003b;
        public static final int Read_EPC=0x7f070002;
        public static final int Read_EPC_data=0x7f070004;
        public static final int Read_EPC_num=0x7f070005;
        public static final int Read_TID=0x7f070006;
        public static final int Read_numerical_order=0x7f070003;
        public static final int ReadpowerFail=0x7f07000f;
        public static final int ReadpowerSuccess=0x7f070010;
        public static final int Receive_regulator_parameters=0x7f07003e;
        public static final int Search=0x7f070013;
        public static final int SetpowerFail=0x7f07000d;
        public static final int SetpowerSuccess=0x7f07000e;
        public static final int Start=0x7f070044;
        public static final int Stop=0x7f070045;
        public static final int Success=0x7f070047;
        public static final int Time_Space=0x7f070043;
        public static final int Total=0x7f070048;
        public static final int WriteError00=0x7f070030;
        public static final int WriteError10=0x7f070036;
        public static final int WriteError16=0x7f070037;
        public static final int WriteErrorB0=0x7f070035;
        public static final int WriteErrorB3=0x7f070031;
        public static final int WriteErrorB4=0x7f070032;
        public static final int WriteErrorBB=0x7f070033;
        public static final int WriteErrorBF=0x7f070034;
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int initializing=0x7f070024;
        public static final int lable_Perma_Open=0x7f070021;
        public static final int lable_Perma_not_RW=0x7f070022;
        public static final int lable_lock=0x7f070020;
        public static final int lable_open=0x7f07001f;
        public static final int magicpower=0x7f070009;
        public static final int menuLock=0x7f07002c;
        public static final int menuRead=0x7f07002a;
        public static final int menuSet=0x7f07002b;
        public static final int menucleardata=0x7f07002e;
        public static final int menuexport=0x7f07002d;
        public static final int menuhelp=0x7f07002f;
        public static final int nodata=0x7f070029;
        public static final int powerabout=0x7f070012;
        public static final int savedata=0x7f070027;
        public static final int savefailed=0x7f070026;
        public static final int saveing=0x7f070028;
        public static final int savesuccess=0x7f070025;
        public static final int setpowerhint=0x7f070011;
        public static final int stopRead_EPC=0x7f070007;
        public static final int stopRead_TID=0x7f070008;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
        public static final int progress_dialog=0x7f080002;
    }
}
